CREATE TABLE `User` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`user_type`	INTEGER NOT NULL,
	`name`	VARCHAR(30) NOT NULL,
	`surname`	VARCHAR(30) NOT NULL,
	`avatar`	VARCHAR(30) NOT NULL,
	`email`	VARCHAR(60) NOT NULL UNIQUE,
	`password`	VARCHAR(130) NOT NULL
);
CREATE TABLE `ShoppingListCategory` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name`	VARCHAR(30) NOT NULL,
	`description`	VARCHAR(30),
	`image`	VARCHAR(30) NOT NULL
);
CREATE TABLE `ShoppingList` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name`	VARCHAR(30) NOT NULL,
	`description`	VARCHAR(30) NOT NULL,
	`image`	VARCHAR(30) NOT NULL,
	`category`	INTEGER NOT NULL,
	FOREIGN KEY(`category`) REFERENCES ShoppingListCategory(id)
);
CREATE TABLE `ProductCategory` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name`	VARCHAR(30) NOT NULL,
	`description`	VARCHAR(30),
	`image`	VARCHAR(30) NOT NULL
);
CREATE TABLE `Product` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name`	VARCHAR(30) NOT NULL,
	`logo`	VARCHAR(30) NOT NULL,
	`creator`	INTEGER,
	`category`	INTEGER NOT NULL,
	FOREIGN KEY(`creator`) REFERENCES User(id),
	FOREIGN KEY(`category`) REFERENCES ProductCategory(id)
);
CREATE TABLE `Photo` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`photo`	VARCHAR(30) NOT NULL,
	`product`	INTEGER NOT NULL,
	FOREIGN KEY(`product`) REFERENCES Product(id)
);
CREATE TABLE `Permission` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`user`	INTEGER NOT NULL,
	`list`	INTEGER NOT NULL,
	`permission`	INTEGER NOT NULL,
	FOREIGN KEY(`user`) REFERENCES User(id),
	FOREIGN KEY(`list`) REFERENCES ShoppingList(id)
);
CREATE TABLE `ListProducts` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`list`	INTEGER NOT NULL,
	`product`	INTEGER NOT NULL,
	`notes`	VARCHAR(30),
	FOREIGN KEY(`list`) REFERENCES ShoppingList(id),
	FOREIGN KEY(`product`) REFERENCES Product(id)
);
CREATE TABLE `Message` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`message`	VARCHAR(30),
	`list`	INTEGER NOT NULL,
	`user`	INTEGER NOT NULL,
	FOREIGN KEY(`list`) REFERENCES ShoppingList(id),
	FOREIGN KEY(`user`) REFERENCES User(id)
);